<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>prueba_EF</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entidad\Entidad.csproj" />
    <ProjectReference Include="..\GestionBIbliotecaService\Servicio.csproj" />
  </ItemGroup>

</Project>
